### ISSUE TITLE
Unable to find summary file

### ISSUE THREAD

**Issue by e-carlin** [slaclab/slactwin#66]
```
Traceback (most recent call last):
  File "/tmp/user-home/python/sirepo/pkcli/job_cmd.py", line 275, in _do_get_simulation_frame
    return template_common.sim_frame_dispatch(
  File "/tmp/user-home/python/sirepo/template/template_common.py", line 717, in sim_frame_dispatch
    res = o(frame_args)
  File "/tmp/user-home/python/slactwin/template/slactwin.py", line 95, in sim_frame_summaryAnimation
    I = _load_archive(frame_args)
  File "/tmp/user-home/python/slactwin/template/slactwin.py", line 155, in _load_archive
    return impact.Impact.from_archive(
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/lume/base.py", line 479, in from_archive
    c.load_archive(archive_h5)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/impact/impact.py", line 612, in load_archive
    g = h5py.File(fname, 'r')
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '//sdf/group/ad/sw/lume/radiasoft/sirepo-alpha/srv/slactwin_db/lume-impact-live/archive/2024/11/21/54c3d7085cc81257980e41824a51f092.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
```

The name is mapped to /srv/slactwin_db/... inside of the container. For now, manually manipulate the path.

**Comment by robnagler** [comment]
We should probably not remap any of these names, because lume-live writes them.
